{% set version = "2023.0.2" %}
{% set buildnumber = 0 %}

package:
  name: daal4py
  version: {{ version }}

source:
  url: https://github.com/intel/scikit-learn-intelex/archive/{{ version }}.tar.gz
  sha256: e289f49b34f2df3a3c5650c38a0d3080062169a9ba6e4bdbd154a4f0b982800a
  patches:
    # - patches/0001-replace-check_estimator_sparse_data-in-tests.patch
    - patches/0004_set_cmake_python_executable.patch

build:
  number: {{ buildnumber }}
  skip: True  # [not ((win or linux) and x86_64)]
  skip: True  # [py<38]
  # missing_dso_whitelist:      # [osx]
  #   - lib/libc++.1.dylib      # [osx]

requirements:
  build:
    - make  # [linux]
    - {{ compiler('cxx') }}  # [not osx]
    - cmake
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy
    - dal-devel 2023.0.1
    - cython
    - jinja2
    - mpich      # [not win]
    - clang-tools
    - pybind11
  run:
    - python
    - dal 2023.0.1
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pandas
    - scipy
    - scikit-learn
    - xgboost       # [not win and py<=38]
    - lightgbm      # [linux]
    - pytest
    - mpich         # [not win]
  source_files:
    - examples
    - tests
    - daal4py
    - onedal
  commands:
    # Confirm that the _onedal_py_host .so/.pyd file was generated
    # This is especially needed by scikit-learn-intelex.
    - test -f ${PREFIX}/lib/python*/site-packages/onedal/_onedal_py_host*.so  # [unix]
    - if not exist %PREFIX%\\Lib\\site-packages\\onedal\\_onedal_py_host*.pyd exit 1  # [win]
    # Upstream tests
    - cd tests
    - python -c "import daal4py"
    - mpirun -n 4 python -m unittest discover -v -p spmd*.py      # [not win]
    - python -m unittest discover -v -p 'test*[!ex].py'
    - pytest --verbose --pyargs ../daal4py/sklearn/
    - pytest --verbose --pyargs ../onedal/ --deselect="onedal/common/tests/test_policy.py" --deselect="onedal/svm/tests/test_svc.py::test_estimator"
    - python ../examples/daal4py/run_examples.py
    - python -m daal4py ../examples/daal4py/sycl/sklearn_sycl.py

about:
  home: https://intelpython.github.io/daal4py/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - doc/daal4py/third-party-programs.txt
  summary: A convenient Python API to Intel (R) oneAPI Data Analytics Library
  description: |
    <strong>LEGAL NOTICE: Use of this software package is subject to the
    software license agreement (as set forth above, in the license section of
    the installed Conda package and/or the README file) and all notices,
    disclaimers or license terms for third party or open source software
    included in or with the software.</strong>
    <br/><br/>
    EULA: <a href="https://opensource.org/licenses/Apache-2.0" target="_blank">Apache-2.0</a>
    <br/><br/>
  dev_url: https://github.com/intel/scikit-learn-intelex
  doc_url: https://intelpython.github.io/daal4py

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - napetrov
    - Alexsandruss
