# The package daal4py depends on dal and dal-devel packages from the intel_repack-feedstock,
# so be sure to update them before updating daal4py. 
{% set version = "2023.1.1" %}
{% set numpy = "1.19.5" %}  # [py<=39 and not (osx and arm64)]
{% set numpy = "1.21" %}  # [py<=39 and (osx and arm64)]
{% set numpy = "1.22" %}  # [py>39 and py<311]
{% set numpy = "1.23" %}  # [py>=311]

package:
  name: daal4py
  version: {{ version }}

source:
  url: https://github.com/intel/scikit-learn-intelex/archive/{{ version }}.tar.gz
  sha256: 451b8c5e6d3a0f4b147a68ffe37bbddf7fc2e706083ec3e57479ec4421a7d963
  patches:
    - patches/0004_set_cmake_python_executable.patch

build:
  number: 0
  skip: True  # [not ((win or linux or osx) and x86_64)]
  skip: True  # [py<38]

requirements:
  build:
    - make  # [linux or osx]
    - {{ compiler('cxx') }}  # [not osx]
    - cmake
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - python
    - clang-tools
    - cython 0.29.33
    - dal-devel 2023.1.1
    - jinja2
    - mpich      # [not win]
    - numpy {{ numpy }}
    - pip
    - pybind11
    - setuptools
    - wheel
  run:
    - python
    - dal 2023.1.1
    - numpy >={{ numpy }},<1.27.0 

test:
  requires:
    - pandas
    - scipy
    - scikit-learn
    - xgboost       # [not win and py<=38]
    - lightgbm      # [linux]
    - pytest
    - mpich 3.3.2 hc856adb_0  # [linux]
  source_files:
    - examples
    - tests
    - daal4py
    - daal4py/sklearn
    - onedal

about:
  home: https://intelpython.github.io/daal4py/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - doc/daal4py/third-party-programs.txt
  summary: A convenient Python API to Intel (R) oneAPI Data Analytics Library
  description: |
    <strong>LEGAL NOTICE: Use of this software package is subject to the
    software license agreement (as set forth above, in the license section of
    the installed Conda package and/or the README file) and all notices,
    disclaimers or license terms for third party or open source software
    included in or with the software.</strong>
    <br/><br/>
    EULA: <a href="https://opensource.org/licenses/Apache-2.0" target="_blank">Apache-2.0</a>
    <br/><br/>
  dev_url: https://github.com/intel/scikit-learn-intelex
  doc_url: https://intelpython.github.io/daal4py

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - napetrov
    - Alexsandruss
